echo 'Converting region file coordinate system syntax'
mkdir /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/
ds9 /home/jpbreuer/Chandra_data/a2256/merged/scaled_broad_flux_fov_sps.fits &
sleep 10
xpaset -p ds9 lower
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_0.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_0_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_1.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_1_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_2.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_2_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_3.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_3_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_4.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_4_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_5.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_5_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_6.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_6_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_7.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_7_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_8.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_8_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_9.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_9_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_10.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_10_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_11.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_11_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_12.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_12_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_13.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_13_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_14.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_14_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_15.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_15_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_16.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_16_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_17.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_17_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_18.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_18_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_19.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_19_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_20.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_20_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_21.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_21_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_22.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_22_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_23.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_23_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_24.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_24_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_25.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_25_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_26.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_26_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_27.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_27_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_28.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_28_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_29.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_29_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_30.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_30_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_31.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_31_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_32.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_32_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_33.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_33_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_34.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_34_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_35.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_35_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_36.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_36_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_37.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_37_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_38.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_38_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_39.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_39_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_40.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_40_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_41.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_41_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_42.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_42_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_43.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_43_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_44.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_44_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_45.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_45_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_46.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_46_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_47.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_47_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_48.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_48_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_49.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_49_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_50.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_50_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_51.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_51_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_52.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_52_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_53.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_53_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_54.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_54_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_55.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_55_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_56.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_56_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_57.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_57_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_58.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_58_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_59.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_59_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_60.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_60_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_61.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_61_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_62.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_62_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_63.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_63_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_64.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_64_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_65.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_65_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_66.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_66_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_67.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_67_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_68.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_68_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_69.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_69_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_70.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_70_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_71.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_71_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_72.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_72_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_73.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_73_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_74.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_74_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_75.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_75_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_76.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_76_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_77.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_77_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_78.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_78_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_79.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_79_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_80.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_80_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_81.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_81_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_82.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_82_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_83.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_83_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_84.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_84_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_85.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_85_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_86.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_86_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_87.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_87_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_88.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_88_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_89.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_89_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_90.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_90_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_91.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_91_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_92.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_92_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_93.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_93_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_94.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_94_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_95.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_95_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_96.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_96_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_97.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_97_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_98.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_98_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_99.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_99_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_100.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_100_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_101.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_101_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_102.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_102_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_103.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_103_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_104.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_104_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_105.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_105_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_106.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_106_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_107.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_107_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_108.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_108_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_109.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_109_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_110.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_110_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_111.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_111_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_112.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_112_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_113.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_113_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_114.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_114_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_115.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_115_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_116.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_116_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_117.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_117_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_118.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_118_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_119.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_119_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_120.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_120_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_121.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_121_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_122.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_122_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_123.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_123_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_124.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_124_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_125.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_125_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_126.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_126_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_127.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_127_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_128.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_128_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_129.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_129_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_130.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_130_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_131.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_131_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_132.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_132_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_133.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_133_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_134.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_134_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_135.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_135_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_136.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_136_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_137.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_137_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_138.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_138_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_139.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_139_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_140.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_140_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_141.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_141_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_142.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_142_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_143.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_143_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_144.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_144_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_145.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_145_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_146.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_146_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_147.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_147_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_148.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_148_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_149.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_149_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_150.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_150_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_151.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_151_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_152.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_152_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_153.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_153_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_154.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_154_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_155.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_155_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_156.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_156_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_157.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_157_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_158.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_158_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_159.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_159_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_160.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_160_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_161.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_161_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_162.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_162_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_163.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_163_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_164.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_164_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_165.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_165_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_166.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_166_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_167.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_167_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 regions load /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/xaf_168.reg
xpaset -p ds9 regions format ciao
xpaset -p ds9 regions system wcs
xpaset -p ds9 regions skyformat sexagesimal
xpaset -p ds9 regions save /home/jpbreuer/Chandra_data/a2256/merged/contbin_sn70_smooth100/outreg/sex/xaf_168_sex.reg
xpaset -p ds9 regions delete all
xpaset -p ds9 exit

echo 'Converting region file coordinate system syntax... Done!'

