mkdir /home/jpbreuer/Chandra_data/a2256/specfile_output/results_sn70_smooth100/xspec
cp xspecfitting.sh /home/jpbreuer/Chandra_data/a2256/specfile_output
xspec - reg_0_xspec_fit.script
xspec - reg_1_xspec_fit.script
xspec - reg_2_xspec_fit.script
xspec - reg_3_xspec_fit.script
xspec - reg_4_xspec_fit.script
xspec - reg_5_xspec_fit.script
xspec - reg_6_xspec_fit.script
xspec - reg_7_xspec_fit.script
xspec - reg_8_xspec_fit.script
xspec - reg_9_xspec_fit.script
xspec - reg_10_xspec_fit.script
xspec - reg_11_xspec_fit.script
xspec - reg_12_xspec_fit.script
xspec - reg_13_xspec_fit.script
xspec - reg_14_xspec_fit.script
xspec - reg_15_xspec_fit.script
xspec - reg_16_xspec_fit.script
xspec - reg_17_xspec_fit.script
xspec - reg_18_xspec_fit.script
xspec - reg_19_xspec_fit.script
xspec - reg_20_xspec_fit.script
xspec - reg_21_xspec_fit.script
xspec - reg_22_xspec_fit.script
xspec - reg_23_xspec_fit.script
xspec - reg_24_xspec_fit.script
xspec - reg_25_xspec_fit.script
xspec - reg_26_xspec_fit.script
xspec - reg_27_xspec_fit.script
xspec - reg_28_xspec_fit.script
xspec - reg_29_xspec_fit.script
xspec - reg_30_xspec_fit.script
xspec - reg_31_xspec_fit.script
xspec - reg_32_xspec_fit.script
xspec - reg_33_xspec_fit.script
xspec - reg_34_xspec_fit.script
xspec - reg_35_xspec_fit.script
xspec - reg_36_xspec_fit.script
xspec - reg_37_xspec_fit.script
xspec - reg_38_xspec_fit.script
xspec - reg_39_xspec_fit.script
xspec - reg_40_xspec_fit.script
xspec - reg_41_xspec_fit.script
xspec - reg_42_xspec_fit.script
xspec - reg_43_xspec_fit.script
xspec - reg_44_xspec_fit.script
xspec - reg_45_xspec_fit.script
xspec - reg_46_xspec_fit.script
xspec - reg_47_xspec_fit.script
xspec - reg_48_xspec_fit.script
xspec - reg_49_xspec_fit.script
xspec - reg_50_xspec_fit.script
xspec - reg_51_xspec_fit.script
xspec - reg_52_xspec_fit.script
xspec - reg_53_xspec_fit.script
xspec - reg_54_xspec_fit.script
xspec - reg_55_xspec_fit.script
xspec - reg_56_xspec_fit.script
xspec - reg_57_xspec_fit.script
xspec - reg_58_xspec_fit.script
xspec - reg_59_xspec_fit.script
xspec - reg_60_xspec_fit.script
xspec - reg_61_xspec_fit.script
xspec - reg_62_xspec_fit.script
xspec - reg_63_xspec_fit.script
xspec - reg_64_xspec_fit.script
xspec - reg_65_xspec_fit.script
xspec - reg_66_xspec_fit.script
xspec - reg_67_xspec_fit.script
xspec - reg_68_xspec_fit.script
xspec - reg_69_xspec_fit.script
xspec - reg_70_xspec_fit.script
xspec - reg_71_xspec_fit.script
xspec - reg_72_xspec_fit.script
xspec - reg_73_xspec_fit.script
xspec - reg_74_xspec_fit.script
xspec - reg_75_xspec_fit.script
xspec - reg_76_xspec_fit.script
xspec - reg_77_xspec_fit.script
xspec - reg_78_xspec_fit.script
xspec - reg_79_xspec_fit.script
xspec - reg_80_xspec_fit.script
xspec - reg_81_xspec_fit.script
xspec - reg_82_xspec_fit.script
xspec - reg_83_xspec_fit.script
xspec - reg_84_xspec_fit.script
xspec - reg_85_xspec_fit.script
xspec - reg_86_xspec_fit.script
xspec - reg_87_xspec_fit.script
xspec - reg_88_xspec_fit.script
xspec - reg_89_xspec_fit.script
xspec - reg_90_xspec_fit.script
xspec - reg_91_xspec_fit.script
xspec - reg_92_xspec_fit.script
xspec - reg_93_xspec_fit.script
xspec - reg_94_xspec_fit.script
xspec - reg_95_xspec_fit.script
xspec - reg_96_xspec_fit.script
xspec - reg_97_xspec_fit.script
xspec - reg_98_xspec_fit.script
xspec - reg_99_xspec_fit.script
xspec - reg_100_xspec_fit.script
xspec - reg_101_xspec_fit.script
xspec - reg_102_xspec_fit.script
xspec - reg_103_xspec_fit.script
xspec - reg_104_xspec_fit.script
xspec - reg_105_xspec_fit.script
xspec - reg_106_xspec_fit.script
xspec - reg_107_xspec_fit.script
xspec - reg_108_xspec_fit.script
xspec - reg_109_xspec_fit.script
xspec - reg_110_xspec_fit.script
xspec - reg_111_xspec_fit.script
xspec - reg_112_xspec_fit.script
xspec - reg_113_xspec_fit.script
xspec - reg_114_xspec_fit.script
xspec - reg_115_xspec_fit.script
xspec - reg_116_xspec_fit.script
xspec - reg_117_xspec_fit.script
xspec - reg_118_xspec_fit.script
xspec - reg_119_xspec_fit.script
xspec - reg_120_xspec_fit.script
xspec - reg_121_xspec_fit.script
xspec - reg_122_xspec_fit.script
xspec - reg_123_xspec_fit.script
xspec - reg_124_xspec_fit.script
xspec - reg_125_xspec_fit.script
xspec - reg_126_xspec_fit.script
xspec - reg_127_xspec_fit.script
xspec - reg_128_xspec_fit.script
xspec - reg_129_xspec_fit.script
xspec - reg_130_xspec_fit.script
xspec - reg_131_xspec_fit.script
xspec - reg_132_xspec_fit.script
xspec - reg_133_xspec_fit.script
xspec - reg_134_xspec_fit.script
xspec - reg_135_xspec_fit.script
xspec - reg_136_xspec_fit.script
xspec - reg_137_xspec_fit.script
xspec - reg_138_xspec_fit.script
xspec - reg_139_xspec_fit.script
xspec - reg_140_xspec_fit.script
xspec - reg_141_xspec_fit.script
xspec - reg_142_xspec_fit.script
xspec - reg_143_xspec_fit.script
xspec - reg_144_xspec_fit.script
xspec - reg_145_xspec_fit.script
xspec - reg_146_xspec_fit.script
xspec - reg_147_xspec_fit.script
xspec - reg_148_xspec_fit.script
xspec - reg_149_xspec_fit.script
xspec - reg_150_xspec_fit.script
xspec - reg_151_xspec_fit.script
xspec - reg_152_xspec_fit.script
xspec - reg_153_xspec_fit.script
xspec - reg_154_xspec_fit.script
xspec - reg_155_xspec_fit.script
xspec - reg_156_xspec_fit.script
xspec - reg_157_xspec_fit.script
xspec - reg_158_xspec_fit.script
xspec - reg_159_xspec_fit.script
xspec - reg_160_xspec_fit.script
xspec - reg_161_xspec_fit.script
xspec - reg_162_xspec_fit.script
xspec - reg_163_xspec_fit.script
xspec - reg_164_xspec_fit.script
xspec - reg_165_xspec_fit.script
xspec - reg_166_xspec_fit.script
xspec - reg_167_xspec_fit.script
xspec - reg_168_xspec_fit.script
xspec - reg_169_xspec_fit.script
xspec - reg_170_xspec_fit.script
xspec - reg_171_xspec_fit.script
xspec - reg_172_xspec_fit.script
xspec - reg_173_xspec_fit.script
xspec - reg_174_xspec_fit.script
xspec - reg_175_xspec_fit.script
xspec - reg_176_xspec_fit.script
xspec - reg_177_xspec_fit.script
xspec - reg_178_xspec_fit.script
xspec - reg_179_xspec_fit.script
xspec - reg_180_xspec_fit.script
xspec - reg_181_xspec_fit.script
xspec - reg_182_xspec_fit.script
xspec - reg_183_xspec_fit.script
xspec - reg_184_xspec_fit.script
xspec - reg_185_xspec_fit.script
xspec - reg_186_xspec_fit.script
xspec - reg_187_xspec_fit.script
xspec - reg_188_xspec_fit.script
xspec - reg_189_xspec_fit.script
xspec - reg_190_xspec_fit.script
xspec - reg_191_xspec_fit.script
xspec - reg_192_xspec_fit.script
xspec - reg_193_xspec_fit.script
xspec - reg_194_xspec_fit.script
xspec - reg_195_xspec_fit.script
xspec - reg_196_xspec_fit.script
xspec - reg_197_xspec_fit.script
